[build]
  command = "cd /src/functions && npm install && cd / && npm run build"
  publish = "dist"
  functions = "./src/functions"

[dev]
  command = "npm run start"
  framework = "#custom"
  publish = "dist"
  port = 3000
  targetPort = 8181
  NODE_ENV = "development"
  functionsPort = 34567

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production]
  environment = { NODE_VERSION = "10.15.3", NODE_ENV = "production" }
