[build]
  base = "/"
  command = "cd /opt/build/repo/src/functions && npm i && cd / && npm i && npm run build"
  publish = "dist"
  functions = "./src/functions"

[dev]
  command = "npm run start"
  framework = "#custom"
  publish = "dist"
  port = 3000
  targetPort = 8181
  NODE_ENV = "development"
  functionsPort = 34567

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
